### ISSUE TITLE
TypeScript Error: DevCycleClientsideProvider Cannot Be Used as JSX Component

### ISSUE THREAD

**Issue by sanjaysah101** [DevCycleHQ/js-sdks#1010]
## Description

When using `DevCycleClientsideProvider` in a Next.js 15 app with TypeScript, there's a type error indicating that the component cannot be used as a JSX component.

## Error Message

```typescript
'DevCycleClientsideProvider' cannot be used as a JSX component.
  Its type '({ context, children, }: DevCycleClientsideProviderProps) => Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not a valid JSX element type.
    Type '({ context, children, }: DevCycleClientsideProviderProps) => Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not assignable to type 'ReactNode'
```

## Reproduction Steps

1. Create a new Next.js 15 project with TypeScript
2. Install `@devcycle/nextjs-sdk`
3. Try to use `DevCycleClientsideProvider` in layout.tsx:

```typescript
import { DevCycleClientsideProvider } from '@devcycle/nextjs-sdk'
import { getClientContext } from '@/lib/devcycle/config'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <DevCycleClientsideProvider context={getClientContext()}>
      {children}
    </DevCycleClientsideProvider>
  )
}
```

## Environment
- Next.js: 15.0.3
- TypeScript: 5.5.4
- @devcycle/next-sdk: 2.7.2
- react: 18.3.1,
- react-dom: 18.3.1,
- eslint: 8.57.1,
- eslint-config-next: 15.0.3,

## Expected Behavior
The `DevCycleClientsideProvider` should work as a valid JSX component without TypeScript errors.

## Additional Context
This seems to be related to the component returning a Promise<ReactElement> instead of ReactNode directly, which causes type incompatibility in Next.js 15's stricter TypeScript setup.

**Comment by suthar26** [comment]
Hi @sanjaysah101, 
I cannot properly repro this. I followed the steps in our [nextjs SDK docs](https://docs.devcycle.com/sdk/client-side-sdks/nextjs/nextjs-install) but dont see any TypeScript errors. 

here is how my RootLayout looks 
```
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DevCycleClientsideProvider context={getClientContext()}>
          {children}
        </DevCycleClientsideProvider>
      </body>
    </html>
  )
}
```
The layout needs the `<head>` and `<body>` tags to work as expected for me. do you want to give it another try with a fresh install with `npx create-next-app@latest` and follow the SDK docs to see if you still see the issue? I see the same return type of `Promise<ReactElement>`. 

following is the package versions I got with the fresh install
```
        "@devcycle/nextjs-sdk": "^2.7.2",
        "next": "15.0.4",
        "react": "^19.0.0",
        "react-dom": "^19.0.0"
         
         "devDependencies":{
           "eslint": "^8",
           "eslint-config-next": "15.0.4",
          }
```

**Comment by sanjaysah101** [comment]
Hi @suthar26, you can test and reproduce this issue here https://github.com/sanjaysah101/flag-feed

**Comment by suthar26** [comment]
please use the [Nextjs upgrade helper](https://nextjs.org/docs/app/building-your-application/upgrading/version-15) note that you are using react 18 while the new minimum version is react 19  

`npx @next/codemod@canary upgrade latest` this will do the job for you

**Comment by sanjaysah101** [comment]
Hi @suthar26, It works for me after updating to Next Js 15 & React 19
