### ISSUE TITLE
Provide option to disable real-time updates

### ISSUE THREAD

**Issue by alxgrk** [DevCycleHQ/js-sdks#468]
Hi,

after successfully using Node.js SDK, I wanted to try integrating your library in an Angular app. It works as expected, so thanks for that.

What I realized though is that there are 3 types of requests:
- https://sdk-api.devcycle.com/ -> for retrieving flag values
- https://events.devcycle.com/v1/events -> for posting user events
- https://realtime.ably.io/ -> SSE provider connection

In the end, my motivation is to hide these calls behind my custom domain as explained [here](https://docs.devcycle.com/sdk/features/custom-domains), but since I assume that this will only work for `*.devcycle.com` domains & because I don't need real-time updates, I wanted to know if it is possible to completely disable that feature.

If not yet possible to disable via configuration, is this something you'd expect to be implemented in the near future?

Best regards,
Alex

**Comment by cdruxerman** [comment]
Hi Alex, I'm checking with our team on this and will make sure someone gets back to you early next week.

Best,
Cobi

**Comment by kaushalkapasi** [comment]
Hey @alxgrk ,

We've just published a new version of the JS SDK ([1.9.4](https://www.npmjs.com/package/@devcycle/devcycle-js-sdk/v/1.9.4)) that adds an initialization option of `disableRealtimeUpdates` that you can set to `true` which will prevent the Streaming Connection from being established!

Let us know if this helps with your use-case! 
Thanks

**Comment by alxgrk** [comment]
Thank you, @kaushalkapasi . Just tested it - working as expected 👍
