### ISSUE TITLE
@devcycle/devcycle-js-sdk shows "Failed to parse source map" warnings in the console

### ISSUE THREAD

**Issue by LuckyLuo** [DevCycleHQ/js-sdks#488]
I used "@devcycle/devcycle-react-sdk": "^1.9.1" and started my test app, but got those "Failed to parse source map" warnings from @devcycle/devcycle-js-sdk

WARNING in ./node_modules/@devcycle/devcycle-js-sdk/src/utils.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/test/sdk/js/src/utils.ts' file: Error: ENOENT: no such file or directory, open '/Users/test/sdk/js/src/utils.ts'

It tried to find those source files from my test project.

**Comment by nikolasleblanc** [comment]
Hey @LuckyLuo, appreciate your patience. Wanted to let you know that we're working on this and will keep you posted!

**Comment by LuckyLuo** [comment]
thanks!

**Comment by nsalamad** [comment]
Hey @LuckyLuo , we've released version [1.9.4](https://www.npmjs.com/package/@devcycle/devcycle-react-sdk) of the SDK which addresses this issue. Thanks again for your patience!

**Comment by LuckyLuo** [comment]
Awesome! thanks for the fix!
