### ISSUE TITLE
Client does not remove pagehide event listener when closed

### ISSUE THREAD

**Issue by WillsB3** [DevCycleHQ/js-sdks#550]
Hey DevCycle team,

This is not affecting me in any way, but I wanted to point it out as it may result in a tricky-to-debug problem for someone else.

In `initializeDevCycle` an event handler is registered for the `pagehide` event ([source](https://github.com/DevCycleHQ/js-sdks/blob/90da9830cc7d6e3abb8a420e66602fbe10ad437e/sdk/js/src/index.ts#L119-L121)). As far as I can tell this event handler is never removed when a client is closed. There is also an event handler registration for the `visibilitychange` event when the client is created but this handler appears to be being cleaned up properly as part of the client's `close` method.

**Comment by kaushalkapasi** [comment]
Hey @WillsB3, thanks for raising this issue. Going to investigate & see what we can do to fix it!

**Comment by kaushalkapasi** [comment]
@WillsB3 we've released a new version of the JS SDK [1.13.7](https://www.npmjs.com/package/@devcycle/js-client-sdk) with a fix for this 😄

**Comment by WillsB3** [comment]
Excellent, thanks :)
