### ISSUE TITLE
@devcycle/js-client-sdk depends on window object

### ISSUE THREAD

**Issue by themastersoda** [DevCycleHQ/js-sdks#708]
JS SDK depends on `window` object being present, which does not exist in browser extensions built on manifest v3. NodeJS SDK on the other hand, depends on packages specific to NodeJS, which leaves no options to use in extension service workers. 

From looking at the code, usages of `window.localStorage`, `window.navigator.userAgent` and `window.addEventListener` are the only instances where a `window` is needed. Hovewer, it is assumed that if `window.addEventListener` does not exist, this must be a react native app.

**Comment by jonathannorris** [comment]
Hey @themastersoda can you give the `@devcycle/js-cloud-server-sdk` SDK a try? 

https://github.com/DevCycleHQ/js-sdks/tree/main/sdk/js-cloud-server

This iteration of the SDK is designed to be used in service worker environments like Cloudflare Workers, and doesn't require NodeJS or Window functions. We will also take a look to see if we can make the core JS SDK more generic and potentially not tied to `window` functions.

**Comment by jonathannorris** [comment]
Hey @themastersoda let us know if you need any further help with this.

**Comment by themastersoda** [comment]
Hey, sorry for late reply. I've checked the cloud sdk, but it's not working well on the client as it does not seem to have the ability to subscribe to feature changes

**Comment by leslie-lau** [comment]
Hey @themastersoda, appreciate you trying that out! We'll be planning to update our SDK to eliminate the need for window functions. We'll keep you posted once we have more details!

**Comment by leslie-lau** [comment]
Hi @themastersoda just wanted to update you that we're working on the changes. We'll reach out if we have any questions or if it's ready for testing!

**Comment by cdruxerman** [comment]
@themastersoda I just wanted to give you another update here. This project has been taking a bit longer than expected, but we are still planning on making the changes. I expect we should have a further update within a few weeks.

**Comment by themastersoda** [comment]
Thanks for the heads up, it's nice to see that you're making progress! 🥳

**Comment by cdruxerman** [comment]
@themastersoda this should be resolved in v1.23.0 of the SDK. Would you mind giving it a try and letting us know if it works for you?

**Comment by elliotCamblor** [comment]
Going to close this issue now that we've released v1.23.0. Let us know if you have any additional questions/issues!
