### ISSUE TITLE
Event queue not fully cleaned up on close

### ISSUE THREAD

**Issue by walmor-rematter** [DevCycleHQ/js-sdks#774]
I'm integrating our backend with `@devcycle/nodejs-server-sdk` and having a very particular issue related to hot reloading and needing to initialize the lib multiple times by calling `initializeDevCycle`.

We have a custom hot reload mechanism that does not shut down the process. To summarize, it simply rebuilds, clears caches, and restarts the express app on the fly. Thus, imported packages (node_modules) are not reloaded after changing a file, making it very fast. However, when the app restarts and calls the `initializeDevCycle` for the second time, we get this error:

```
Event Queue already exists for sdkKey: ${sdkKey} you can only initialize the DevCycle SDK once per sdkKey
```

We're calling `devCycleClient.close()` when the app shuts down but that doesn't solve the problem. Looking at the code, I can see that the `close()` method on the `DevCycleClient` calls the `cleanup` method on the `EventQueue` but that's not enough. I believe that a potential solution is to also call the `cleanupEventQueue(sdkKey)` method when closing the client, but I'm not sure if that has any drawbacks.

That's what I'm doing to workaround the problem for now, essentially this:

```typescript
import { getBucketingLib } from '@devcycle/nodejs-server-sdk/src/bucketing';

export const closeFeatureFlagsClient = async () => {
  if (devCycleClient) {
    await devCycleClient.close();
  }
  
  getBucketingLib().cleanupEventQueue(DEV_CYCLE_SERVER_KEY);
};
```

It works, but I believe the `cleanupEventQueue` method was only intended to be used internally.

Another solution I can see is to add an option to the `initializeDevCycle` method that would allow us to continue normally even if the queue was already created, or something like that.

**Comment by cdruxerman** [comment]
@walmor-rematter I'll have our team look into this for you

**Comment by cdruxerman** [comment]
Also @walmor-rematter sorry for all the name and label changes. We just started trying out the github/linear sync and I wasn't expecting those

**Comment by walmor-rematter** [comment]
Hey @elliotCamblor,

Got it, well, if fully cleaning up the queue on close is not possible then, yes, allowing us to initialize the SDK multiple times would be very helpful.

I'll keep my workaround for now until we have a better solution.

Thank you for the quick reply!
