### ISSUE TITLE
Intermittent issue with `initializeDevCycle` function

### ISSUE THREAD

**Issue by gleidin** [DevCycleHQ/js-sdks#865]
Hi! I've been implementing the `@devcycle/nodejs-server-sdk` in my node backend code, and I am facing some issues with initializing the SDK incorrectly. The configuration looks right, but I noticed that the SDK fails to initialize (a few times) 

The application I am integrating it is using:
**Node:** v16.20.2 (npm v8.19.4)
**@devcycle/nodejs-server-sdk**: ^1.30.0

Init code snippet:
```  typescript
const DEVCYCLE_SERVER_SDK_KEY = process.env.DEVCYCLE_SERVER_SDK_KEY ?? '';
let devcycleClient: DevCycleClient;

export const initDevCycle = async () => {
    devcycleClient = await initializeDevCycle(DEVCYCLE_SERVER_SDK_KEY, {
        logger: logger,
        logLevel: 'debug',
        enableCloudBucketing: false,
        configPollingIntervalMS: 10 * 1000,
    }).onClientInitialized((err) => {
        logger.error(`Fail to initialize DevCycle: ${err}`);
    });
    devcycleClient.isInitialized && logger.info('Initialized DevCycle');
};
```

Looking at the logs using the debug mode, I can see:
```
DEBUG: Requesting new config for https://config-cdn.devcycle.com/config/v1/server/dvc_server_xxx.json, etag: undefined, last-modified: undefined
ERROR: Error initializing DevCycle: Error: Config data is not set. in assembly/managers/configDataManager.ts:11:9
ERROR: Fail to initialize DevCycle: undefined
``` 

What is wrong with this configuration? I see that the`configDataManager` is validating the sdk value. However, after digging my code I noticed that the SDK value is being inserted correctly. I tried to remove all extra configuration values too, with no difference in the outcome. As mentioned at the top, it worked a few times and stopped working.

**Comment by leslie-lau** [comment]
Hi @gleidin thanks for the message! We'll take a look at the issue and get back to you if we have any questions or updates.

**Comment by gleidin** [comment]
thanks for the fast response @leslie-lau. 

I'm just adding more info, the tracking portion of the SDK is even working, and the pulling too. However, when I try to verify variables it encounters issues, adding a few logs below:
```
DEBUG: Requesting new config for https://config-cdn.devcycle.com/config/v1/server/dvc_server_xxx.json, etag: undefined, last-modified: undefined
DEBUG: Downloaded config, status: 200, etag: W/"6c17445b4eb5665f194de50c318515af"
DEBUG: Flush Payloads: [{"records":[{"user":{"user_id":"xxx0@Gleidson-xxx-MacBook-Pro.xxx","createdDate":"2024-05-29T14:54:58.735Z","lastSeenDate":"2024-05-29T14:54:58.735Z","platform":"NodeJS","platformVersion":"v16.20.2","sdkType":"server","sdkVersion":"1.30.0","hostname":"xxxMacBook-Pro.local"},"events":[{"type":"sdkConfig","target":"https://config-cdn.devcycle.com/config/v1/server/dvc_server_xxx.json","user_id":"xxx@Gleidson-Bragas-MacBook-Pro.local","date":"2024-05-29T14:54:58.735Z","clientDate":"2024-05-29T14:54:58.735Z","value":87.0,"featureVars":{"664fadc6483b2a7bfd1b2c78":"664fadc6483b2a7bfd1b2d4d","66563472895fcae3b71af991":"66563472895fcae3b71af99b"},"metaData":{"clientUUID":"46b501bf-555a-4de2-8dae-b9b7175634b0","resEtag":"W/\"6c17445b4eb5665f194de50c318515af\"","resLastModified":"Tue, 28 May 2024 19:45:56 GMT","resRayId":"88b752a17e283559-CNF","resStatus":200}}]}],"payloadId":"a2105d96-11d7-4d63-9d68-7348eff87ac1","eventCount":1}]
DEBUG: DVC Flush 1 Events, for 1 Users
```
Whenever I try to get variables value:
```
WARN: variable called before DevCycleClient initialized, returning default value
```

**Comment by leslie-lau** [comment]
Hi @gleidin, we've released a new version of our [NodeJS SDK](https://www.npmjs.com/package/@devcycle/nodejs-server-sdk), version `1.30.1` which should fix the intermittent issues with initializing DevCycle. Could you give that a shot and let us know if that resolves the issue? Thank you!

**Comment by gleidin** [comment]
thanks @leslie-lau you did the trick! It works now, I've tested it a couple of times here and everything is fine! 

Thanks for the fast fix!!! I really appreciate it! Gonna close the issue. 😄
