### ISSUE TITLE
Realtime updates not working with next js

### ISSUE THREAD

**Issue by jameskajon** [DevCycleHQ/js-sdks#885]
I have a next js app using the app router. I have added the devcycle provider following [these instructions](https://docs.devcycle.com/sdk/client-side-sdks/nextjs/nextjs-usage-app). However, after changing a flag, the page never updates. It is only after waiting a bit and doing a hard refresh that the new value for the flag is available for both client and server components. The eventstream does immediately show a change but no update is triggered on the feature flags. What am I doing wrong? I have a minimum reproduction [here](https://github.com/jameskajon/test-devcycle-nextjs)

**Comment by elliotCamblor** [comment]
Hey @jameskajon I'm happy to take a look. Do you happen to be triggering a change to a flag value using the "self-targeting" feature?

**Comment by jameskajon** [comment]
Thank you! No I don't use self targeting. I use development targeting

**Comment by elliotCamblor** [comment]
Cool, thank you! A few more questions for you:
1. Do you see any activity coming from the server after the eventstream message comes in? Any post/get requests going out?
2. Can I get some more detail about the actual change you're triggering? For example: Enabling/disabling the development environment on the feature, changing the variation being served by a targeting rule, updating a variable value within the variations table, etc.

**Comment by jameskajon** [comment]
1. After the eventstream message comes in there is a post to https://events.devcycle.com/v1/events and 
http://localhost:3002. And also a get to http://localhost:3002/?_rsc=r3yhw
1. I have tried toggling the development targeting while the variation is on. And I have tried toggling the variation while the targeting is on

btw I am running this from a build using next start

**Comment by elliotCamblor** [comment]
Thank you, that's very helpful. I'm able to repro now, so I'll be looking into it. Will keep you posted!

**Comment by jameskajon** [comment]
Awesome! Thank you

**Comment by elliotCamblor** [comment]
Hey @jameskajon I just released a new version of the nextjs sdk (v2.2.1) which should resolve the issues you were seeing. 

Don't hesitate to reach out again if you encounter any more issues!

**Comment by jameskajon** [comment]
I can confirm v2.2.1 has fixed the issue. Thank you for fixing it so fast!
