### ISSUE TITLE
Unstructured Logging

### ISSUE THREAD

**Issue by syman447** [DevCycleHQ/js-sdks#993]
https://github.com/DevCycleHQ/js-sdks/blob/db122d798f2691541ed6671b9a3be818c1449040/sdk/nextjs/src/common/invalidateConfig.ts#L15

This log isn't using the `logger` we pass into `setupDevCycle`, so it shows up unstructured in our server logs. Is it possible to have this (and any other server-side logs the SDK may produce) use the provided `logger`?

**Comment by kaushalkapasi** [comment]
Hey @syman447, thanks for raising this. 

This does look like a miss on our part of not using the logger and just using `console.log`, I'll let you know once we have an update.

**Comment by kaushalkapasi** [comment]
Hey @syman447, we decided to cleanup the console.log here all together. The update is released in [`@devcycle/nextjs-sdk@2.6.4`](https://www.npmjs.com/package/@devcycle/nextjs-sdk/v/2.6.4). Let us know if this addresses the concern! Thanks.

**Comment by syman447** [comment]
Awesome thanks! Did a quick search on the nextjs code and it seems like all the remaining `console.*` references are `console.error` so shouldn't be any noisy stuff left. (Would probably still be nice if those error logs were using the logger instance, but that's just a suggestion 😁 Hope to not see any of those errors anyways!)

**Comment by kaushalkapasi** [comment]
We'll definitely keep an eye on that and see if we can migrate the `console.error` to use the logger as well. We'll keep you posted.

**Comment by kaushalkapasi** [comment]
We'll definitely keep an eye on that and see if we can migrate the console.error to use the logger as well. We'll keep you posted.
